# Generated by Django 4.1.7 on 2023-02-28 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_shopping_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_list',
            name='price',
        ),
        migrations.AlterField(
            model_name='shopping_list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
