# Generated by Django 4.1.7 on 2023-03-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shopping_lists',
        ),
        migrations.AddField(
            model_name='shopping_list',
            name='products',
            field=models.ManyToManyField(to='user.product'),
        ),
    ]
